version: "3"
services:
  githubarchive:
    build:
      context: githubArchive/
      dockerfile: Dockerfile
  datastorage:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ../data:/tmp/data
  rabbitmq:
    build:
      context: rabbitManagement/
      dockerfile: Dockerfile
    ports:
      - 8888:15672
  search:
    image: elasticsearch
    ports:
      - 9200:9200
    tty: true
  kibana:
    image: kibana
    ports:
      - 5601:5601
  recommandation:
    build:
      context: .
      dockerfile: ./recommandation/Dockerfile
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./recommandation/data:/data
      - ./recommandation/plugins:/plugins
    tty: true
  prediction:
    build:
      context: .
      dockerfile: ./prediction/Dockerfile
    ports:
      - 8889:8889
      - 4040:4040
    volumes:
      - ./prediction/data:/home/jovyan/data
    tty: true
