version: "3"
services:
  githubarchive:
    build:
      context: githubArchive/
      dockerfile: Dockerfile
    volumes:
      - ./githubArchive/src:/data
  consume-broker:
    build:
      context: githubArchive/
      dockerfile: DockerfileConsumer
    volumes:
      - ./githubArchive/src:/data
  datastorage:
    image: mongo
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    volumes:
      - ./share:/tmp/share
      - mongodata:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    volumes:
      - ./rabbitManagement/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./rabbitManagement/definitions.json:/etc/rabbitmq/definitions.json:ro
  listener-rabbitmq:
    build:
      context: githubArchive
      dockerfile: Dockerfile
  search:
    image: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - ./dbs/esdata1:/usr/share/elasticsearch/data
    tty: true
  kibana:
    image: kibana
    ports:
      - 5601:5601
  recommandation:
    build:
      context: .
      dockerfile: ./recommandation/Dockerfile
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./share:/tmp/share
      - ./dbs/neo4j/data:/data
      - ./dbs/neo4j/plugins:/plugins
    tty: true
  prediction:
    build:
      context: .
      dockerfile: ./prediction/Dockerfile
    ports:
      - 8889:8889
      - 4040:4040
    volumes:
      - ./prediction/data:/home/jovyan/data
    tty: true
volumes:
  mongodata:
