version: "3"
services:
  githubarchive:
    build:
      context: .
      dockerfile: ./githubArchive/Dockerfile
  #commitsimulator:
  #   build:
  #     context: .
  #     dockerfile: ./commitSimulator/Dockerfile
  datastorage:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ../data:/tmp/data
  broker:
    image: rabbitmq:3
  search:
    image: elasticsearch
    ports:
      - 9200:9200
    tty: true
  kibana:
    image: kibana
    ports: 
      - 5601:5601
  recommandation:
    build:
      context: .
      dockerfile: ./recommandation/Dockerfile
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./recommandation/data:/data 
      - ./recommandation/plugins:/plugins
    tty: true
   #prediction:
   #  image: 
