version: "3"
services:
  githubarchive:
    build:
      context: githubArchive/
      dockerfile: Dockerfile
    volumes:
      - ./githubArchive/src:/data
  broker-consumer:
    build:
      context: githubArchive/
      dockerfile: DockerfileConsumer
    volumes:
      - ./githubArchive/src:/data
  datastorage-primary:
    build:
      context: .
      dockerfile: ./datastorage/Dockerfile
    expose: [27017,27018,27019]
    volumes:
      - ./datastorage:/tmp/share
      - mongodataPrimary:/data/db
    command: mongod -smallfiles --bind_ip 0.0.0.0 --replSet rsProjet --dbpath /data/dbRsProjet --storageEngine "mmapv1"
  datastorage-secondary:
    build:
      context: .
      dockerfile: ./datastorage/Dockerfile
    expose: [27017,27018,27019]
    volumes:
      - ./datastorage:/tmp/share
      - mongodataSecondary:/data/db
    command: mongod --smallfiles --bind_ip 0.0.0.0 --replSet rsProjet --dbpath /data/dbRsProjet --storageEngine "mmapv1"
  datastorage-arbitre:
    build:
      context: .
      dockerfile: ./datastorage/Dockerfile
    expose: [27017,27018,27019]
    volumes:
      - ./datastorage:/tmp/share
      - mongodataSecondary:/data/db
    command: mongod --smallfiles --bind_ip 0.0.0.0 --replSet rsProjet --dbpath /data/dbRsProjet --storageEngine "mmapv1"
  mongosetup:
    image: mongo:3.0.6
    volumes:
      - ./datastorage:/scripts
    entrypoint: [ "/scripts/setup.sh" ]
  rabbitmq:
    image: rabbitmq:3-management
    links:
      - datastorage-primary
      - datastorage-secondary
      - datastorage-arbitre
    ports:
      - 15672:15672
    volumes:
      - ./rabbitManagement/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./rabbitManagement/definitions.json:/etc/rabbitmq/definitions.json:ro
  search:
    image: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - ./dbs/esdata1:/usr/share/elasticsearch/data
    tty: true
  kibana:
    image: kibana
    ports:
      - 5601:5601
  recommandation:
    build:
      context: .
      dockerfile: ./recommandation/Dockerfile
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./share:/tmp/share
      - ./dbs/neo4j/data:/data
      - ./dbs/neo4j/plugins:/plugins
    tty: true
  prediction:
    build:
      context: .
      dockerfile: ./prediction/Dockerfile
    ports:
      - 8889:8889
      - 4040:4040
    volumes:
      - ./prediction/data:/home/jovyan/data
    tty: true
volumes:
  mongodataPrimary:
  mongodataSecondary:
