version: "3"
services:
  githubarchive:
    container_name: githubarchive
    build:
      context: githubArchive/
      dockerfile: Dockerfile
    volumes:
      - ./githubArchive/src:/data
  broker-consumer:
    container_name: brokerconsumer
    build:
      context: githubArchive/
      dockerfile: DockerfileConsumer
    volumes:
      - ./githubArchive/src:/data
  datastorage-primary:
    container_name: mongoprimary
    build:
      context: .
      dockerfile: ./datastorage/Dockerfile
    expose: [27017,27018,27019]
    volumes:
      - ./datastorage:/tmp/share
      - mongodataPrimary:/data/db
    command: mongod -smallfiles --bind_ip 0.0.0.0 --replSet rsProjet --dbpath /data/dbRsProjet --storageEngine "mmapv1"
  datastorage-secondary:
    container_name: mongosecondary
    build:
      context: .
      dockerfile: ./datastorage/Dockerfile
    expose: [27017,27018,27019]
    volumes:
      - ./datastorage:/tmp/share
      - mongodataSecondary:/data/db
    command: mongod --smallfiles --bind_ip 0.0.0.0 --replSet rsProjet --dbpath /data/dbRsProjet --storageEngine "mmapv1"
  datastorage-arbitre:
    container_name: mongoarbitre
    build:
      context: .
      dockerfile: ./datastorage/Dockerfile
    expose: [27017,27018,27019]
    volumes:
      - ./datastorage:/tmp/share
      - mongodataSecondary:/data/db
    command: mongod --smallfiles --bind_ip 0.0.0.0 --replSet rsProjet --dbpath /data/dbRsProjet --storageEngine "mmapv1"
  mongosetup:
    container_name: mongosetup
    image: mongo:3.0.6
    volumes:
      - ./datastorage:/scripts
    entrypoint: [ "/scripts/setup.sh" ]
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    links:
      - datastorage-primary
      - datastorage-secondary
      - datastorage-arbitre
    ports:
      - 15672:15672
    volumes:
      - ./rabbitManagement/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./rabbitManagement/definitions.json:/etc/rabbitmq/definitions.json:ro
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    container_name: search
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://search:9200
    tty: true
  neo4j:
    container_name: recommandation
    build:
      context: .
      dockerfile: ./recommandation/Dockerfile
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./share:/tmp/share
      - ./dbs/neo4j/data:/data
      - ./dbs/neo4j/plugins:/plugins
    tty: true
  jupyter-python-spark:
    build:
      context: .
      dockerfile: ./prediction/Dockerfile
    container_name: prediction
    ports:
      - 8889:8889
      - 4040:4040
    volumes:
      - ./prediction/data:/home/jovyan/data
    tty: true
volumes:
  mongodataPrimary:
  mongodataSecondary:
